异常
1.python发生错误时，会创建一个异常对象，如果编写了处理这个异常的代码，程序继
续运行；否则，程序停止，并显示traceback，其中包含有关异常的报告
2. 异常是使用try-except代码块处理
将导致错误代码print(5/0) 放在一个try代码块中。
如果try中的代码运行没问题，将跳过except代码块；
如果try中的代码导致错误，将查找这样的except代码块，并运行其中的代码，即其中指定的错误与引发的错误相同。